Repository geopython/pygeoapi, pull requests merged in 2020-07, with the labels that each got.

#480 Linting openapi
  .travis.yml
  pygeoapi-config.yml
  pygeoapi/openapi.py
Labels: OAFeat, OpenAPI, enhancement

#488 Fix response and schema for queryables in the openapi document
  pygeoapi/openapi.py
Labels: OAFeat

#494 Fixes #493 change ProcessCollection to ProcessList in oapip schema ref
  pygeoapi/openapi.py
Labels: OAProc, bug

#501 Issue 499 - Moving id field of geojson providers to root
  pygeoapi/provider/geojson.py
  tests/data/ne_110m_lakes.geojson
  tests/data/ne_110m_populated_places_simple.geojson
  tests/test_geojson_provider.py
Labels: GSoC, bug
