Repository geopython/pygeoapi, pull requests merged in 2021-05, with the labels that each got.

#691 fix 5 minute install (#686)
  .travis.yml
  pygeoapi-config.yml
  requirements-manager.txt
  requirements-provider.txt
  requirements.txt
Labels: bug

#698 Fix MVT tiles provider broken tile references
  pygeoapi/provider/mvt.py
  pygeoapi/util.py
Labels: OATiles, bug

#701 update OARec metadata models per spec changes
  pygeoapi-config.yml
  tests/data/open.canada.ca/sample-records.tinydb
  tests/load_tinydb_records.py
  tests/test_tinydb_catalogue_provider.py
Labels: OARec

#702 fix Flask blueprints
  pygeoapi/flask_app.py
Labels: bug
