Repository geopython/pygeoapi, pull requests merged in 2021-07, with the labels that each got.

#730 fix response for non-existent collections (#722)
  pygeoapi/api.py
  tests/test_api.py
Labels: bug

#732 update OAProc to latest specification
  .github/workflows/main.yml
  pygeoapi/api.py
  pygeoapi/flask_app.py
  pygeoapi/openapi.py
  pygeoapi/starlette_app.py
Labels: OAProc, enhancement

#723 Add cql-json support for ES
  .github/workflows/main.yml
  docs/source/cql.rst
  docs/source/data-publishing/ogcapi-features.rst
  docs/source/development.rst
  docs/source/index.rst
  pygeoapi/api.py
  pygeoapi/flask_app.py
  pygeoapi/models/__init__.py
  pygeoapi/models/cql.py
  pygeoapi/provider/elasticsearch_.py
  pygeoapi/starlette_app.py
  pygeoapi/util.py
  requirements-dev.txt
  requirements-provider.txt
  requirements-starlette.txt
  requirements.txt
  tests/data/open.canada.ca/nhsl_hazard_threat_all_indicators_s_bc.geojson
  tests/test_elasticsearch__provider.py
Labels: OAFeat, enhancement

#735 update OAProc content models
  docs/source/data-publishing/ogcapi-processes.rst
  pygeoapi/api.py
  pygeoapi/process/hello_world.py
  pygeoapi/templates/processes/process.html
  tests/test_api.py
Labels: OAProc

#744 OARec bbox should be two arrays, not three
  tests/load_tinydb_records.py
Labels: OARec, bug

#746 simplify OAProc parameter handling
  pygeoapi/api.py
Labels: OAProc
