Repository geopython/pygeoapi, pull requests merged in 2022-05, with the labels that each got.

#898 fix MIME types and OpenAPI datetime specification from OGR
  docs/source/plugins.rst
  pygeoapi/api.py
  pygeoapi/provider/ogr.py
Labels: bug

#899 Fix broken tiles collection uri
  pygeoapi/provider/mvt.py
Labels: bug, OATiles

#915 update OARec links based on latest updates in specification
  pygeoapi/templates/collections/items/item.html
  tests/data/open.canada.ca/sample-records.tinydb
  tests/load_tinydb_records.py
  tests/test_tinydb_catalogue_provider.py
Labels: enhancement
