Repository geopython/pygeoapi, pull requests merged in 2022-09, with the labels that each got.

#984 add support for API transactions
  docs/source/configuration.rst
  docs/source/data-publishing/ogcapi-features.rst
  docs/source/data-publishing/ogcapi-records.rst
  docs/source/index.rst
  docs/source/tour.rst
  docs/source/transactions.rst
  pygeoapi/api.py
  pygeoapi/django_/views.py
  pygeoapi/flask_app.py
  pygeoapi/openapi.py
  pygeoapi/provider/base.py
  pygeoapi/provider/elasticsearch_.py
  pygeoapi/provider/tinydb_.py
  pygeoapi/schemas/config/pygeoapi-config-0.x.yml
  pygeoapi/starlette_app.py
  tests/test_api.py
  tests/test_tinydb_catalogue_provider.py
Labels: enhancement

#801 Added build & push to GH container registry & DockerHub
  .github/workflows/containers.yml
  .github/workflows/main.yml
  docs/source/installation.rst
  docs/source/running-with-docker.rst
Labels: enhancement

#997 fix for issue 989 - get Docker build/push working
  .github/workflows/containers.yml
  docker/default.config.yml
  tests/pygeoapi-test-ogr-config.yml
Labels: bug

#998 Update CI Build and Docker status badges
  README.md
Labels: documentation

#996 fix for issue #993 - fix ESRI Provider tests
  .github/workflows/main.yml
  tests/test_esri_provider.py
Labels: bug

#1000 Move flake8 test before provider tests
  .github/workflows/lint.yml
  .github/workflows/main.yml
Labels: enhancement

#1001 Update badges
  README.md
Labels: enhancement, documentation
