Repository geopython/pygeoapi, pull requests merged in 2022-10, with the labels that each got.

#1014 fixes issue #1013 - new URL Dutch RDInfo WFS
  aws-lambda/function/pygeoapi-config.yml
  docker/default.config.yml
  pygeoapi/provider/ogr.py
  tests/pygeoapi-test-ogr-config.yml
Labels: bug

#1015 do not set ES dates as raw
  pygeoapi/provider/elasticsearch_.py
Labels: bug

#985 Upgrade the docker example to ES=8
  docker/examples/elastic/ES/Dockerfile
  docker/examples/elastic/docker-compose.yml
Labels: enhancement

#1025 html point clustering
  pygeoapi/templates/collections/items/index.html
Labels: enhancement, ui
