Repository geopython/pygeoapi, pull requests merged in 2023-04, with the labels that each got.

#1152 API design rule support
  docs/source/configuration.rst
  pygeoapi/api.py
  pygeoapi/config.py
  pygeoapi/django_/settings.py
  pygeoapi/django_/urls.py
  pygeoapi/flask_app.py
  pygeoapi/linked_data.py
  pygeoapi/models/config.py
  pygeoapi/openapi.py
  pygeoapi/process/manager/tinydb_.py
  pygeoapi/provider/sensorthings.py
  pygeoapi/schemas/config/pygeoapi-config-0.x.yml
  pygeoapi/starlette_app.py
  pygeoapi/util.py
  requirements-dev.txt
  tests/pygeoapi-test-config-apirules.yml
  tests/test_api.py
  tests/test_config.py
  tests/test_util.py
  tests/util.py
Labels: enhancement

#1205 various provider fixes
  pygeoapi/provider/azure_.py
  pygeoapi/provider/elasticsearch_.py
  pygeoapi/provider/filesystem.py
Labels: bug

#1216 ES: change PUT update argument
  pygeoapi/provider/elasticsearch_.py
Labels: bug

#1220 add DOI
  README.md
  docs/source/index.rst
Labels: documentation

#1214 add support for ERDDAP Tabledap provider
  docs/source/conf.py
  docs/source/configuration.rst
  docs/source/data-publishing/ogcapi-features.rst
  pygeoapi/plugin.py
  pygeoapi/provider/erddap.py
Labels: enhancement

#1230 add license section to collection if rel=license exists
  pygeoapi/templates/collections/collection.html
Labels: enhancement
