Repository geopython/pygeoapi, pull requests merged in 2024-04, with the labels that each got.

#1605 Safely serialize configuration JSON
  pygeoapi/admin.py
  tests/data/admin/resource-post.json
Labels: bug

#1611 safeguard STAC collection links (#1610)
  pygeoapi/api.py
Labels: bug

#1405 Proposal to split api.py into different files
  .github/workflows/main.yml
  docs/source/development.rst
  pygeoapi/api.py
  pygeoapi/api/__init__.py
  pygeoapi/api/coverages.py
  pygeoapi/api/environmental_data_retrieval.py
  pygeoapi/api/itemtypes.py
  pygeoapi/api/maps.py
  pygeoapi/api/processes.py
  pygeoapi/api/stac.py
  pygeoapi/api/tiles.py
  pygeoapi/django_/views.py
  pygeoapi/flask_app.py
  pygeoapi/openapi.py
  pygeoapi/process/manager/base.py
  pygeoapi/process/manager/dummy.py
  pygeoapi/provider/xarray_.py
  pygeoapi/starlette_app.py
  pygeoapi/util.py
  tests/api/test_api.py
  tests/api/test_coverages.py
  tests/api/test_environmental_data_retrieval.py
  tests/api/test_itemtypes.py
  tests/api/test_maps.py
  tests/api/test_processes.py
  tests/api/test_tiles.py
  tests/conftest.py
  tests/test_api.py
  tests/test_api_ogr_provider.py
  tests/test_postgresql_provider.py
  tests/util.py
Labels: enhancement

#1505 Removed duplicate running of pygeoapi in serve cli command
  pygeoapi/__init__.py
Labels: bug

#1618 Fix indentation error in process.py
  pygeoapi/api/processes.py
Labels: bug

#1446 Included exception info in the logs, if available
  pygeoapi/api/__init__.py
  pygeoapi/api/coverages.py
  pygeoapi/api/environmental_data_retrieval.py
  pygeoapi/api/itemtypes.py
  pygeoapi/api/maps.py
  pygeoapi/api/processes.py
  pygeoapi/api/stac.py
  pygeoapi/api/tiles.py
Labels: stale

#1627 fix missing Django processes endpoints (#1592)
  docs/source/running.rst
  pygeoapi/django_/urls.py
  pygeoapi/django_/views.py
  pygeoapi/flask_app.py
Labels: bug

#1628 PostgreSQL provider: fix paging (#1594)
  pygeoapi/provider/postgresql.py
  tests/test_postgresql_provider.py
Labels: bug

#1631 add striptags to properties rendering
  pygeoapi/templates/collections/items/index.html
Labels: bug
