Repository geopython/pygeoapi, pull requests merged in 2024-06, with the labels that each got.

#1680 1676 Manager pass job_id to processor
  pygeoapi/process/base.py
  pygeoapi/process/manager/base.py
Labels: OGC API - Processes

#1683 Fix SensorthingsAPI Action
  .github/workflows/main.yml
Labels: bug, tests

#1686 fix Django routes (#1685)
  pygeoapi/django_/views.py
Labels: bug

#1687 add translation markers (#1681)
  locale/bs/LC_MESSAGES/messages.po
  locale/de/LC_MESSAGES/messages.po
  locale/en/LC_MESSAGES/messages.po
  locale/fr/LC_MESSAGES/messages.po
  locale/sr/LC_MESSAGES/messages.po
  pygeoapi/templates/collections/index.html
Labels: bug

#1688 Oracle Connection Pooling implementation of issues/1655
  docs/source/data-publishing/ogcapi-features.rst
  pygeoapi/provider/oracle.py
  tests/test_oracle_provider.py
Labels: enhancement, OGC API - Features

#1692 add support for item schema string format (#1691)
  docs/source/introduction.rst
  locale/bs/LC_MESSAGES/messages.po
  locale/de/LC_MESSAGES/messages.po
  locale/en/LC_MESSAGES/messages.po
  locale/fr/LC_MESSAGES/messages.po
  locale/sr/LC_MESSAGES/messages.po
  pygeoapi/api/__init__.py
  pygeoapi/api/itemtypes.py
  pygeoapi/provider/postgresql.py
  pygeoapi/templates/collections/collection.html
  pygeoapi/templates/collections/queryables.html
  pygeoapi/templates/collections/schema.html
  tests/test_postgresql_provider.py
Labels: enhancement

#1697 fix items collection link href
  pygeoapi/api/itemtypes.py
Labels: bug
