Repository geopython/pygeoapi, pull requests merged in 2024-07, with the labels that each got.

#1701 Fix typos
  docker/default.config.yml
  docker/entrypoint.sh
  docs/source/admin-api.rst
  docs/source/configuration.rst
  docs/source/data-publishing/ogcapi-features.rst
  docs/source/data-publishing/stac.rst
  docs/source/language.rst
  docs/source/running.rst
  docs/source/transactions.rst
  pygeoapi/admin.py
  pygeoapi/api/itemtypes.py
  pygeoapi/api/processes.py
  pygeoapi/process/base.py
  pygeoapi/process/manager/base.py
  pygeoapi/provider/base.py
  pygeoapi/provider/base_mvt.py
  pygeoapi/provider/oracle.py
  pygeoapi/provider/sqlite.py
  pygeoapi/provider/xarray_.py
  tests/pygeoapi-test-config-ogr.yml
Labels: documentation

#1706 update translation labels (#1704)
  locale/bs/LC_MESSAGES/messages.po
  locale/de/LC_MESSAGES/messages.po
  locale/en/LC_MESSAGES/messages.po
  locale/fr/LC_MESSAGES/messages.po
  locale/sr/LC_MESSAGES/messages.po
  pygeoapi/templates/_base.html
  pygeoapi/templates/collections/collection.html
  pygeoapi/templates/collections/items/item.html
Labels: bug

#1707 add Spanish translations
  locale/es/LC_MESSAGES/messages.po
Labels: enhancement

#1709 Fix bullet point nesting in docs
  docs/source/data-publishing/ogcapi-coverages.rst
  docs/source/data-publishing/ogcapi-records.rst
  docs/source/data-publishing/ogcapi-tiles.rst
  docs/source/data-publishing/stac.rst
  docs/source/introduction.rst
Labels: documentation

#1705 Disable generic format check for collection_coverage
  pygeoapi/django_/views.py
  pygeoapi/flask_app.py
  pygeoapi/starlette_app.py
Labels: bug

#1713 EDR generic layers UI
  pygeoapi/templates/collections/edr/query.html
Labels: bug

#1714 OAProc: test hello-world process evaluation of None and empty dict
  pygeoapi/process/hello_world.py
Labels: bug

#1715 Fix typo in ogcapi-processes.rst
  docs/source/data-publishing/ogcapi-processes.rst
Labels: bug, documentation

#1716 use identification.url as about link on landing page
  pygeoapi/api/__init__.py
  pygeoapi/templates/landing_page.html
  tests/api/test_api.py
Labels: enhancement, ui

#1720 Update test_tinydb_manager_for_parallel_requests.py
  tests/test_tinydb_manager_for_parallel_requests.py
Labels: bug, OGC API - Processes

#1726 OAProc: fix response type on delete_job (#1721)
  pygeoapi/api/processes.py
  tests/api/test_processes.py
Labels: bug, OGC API - Processes

#1724 add support for TinyDB feature provider
  .github/workflows/main.yml
  docs/source/data-publishing/ogcapi-edr.rst
  docs/source/data-publishing/ogcapi-features.rst
  docs/source/data-publishing/ogcapi-maps.rst
  pygeoapi/plugin.py
  pygeoapi/provider/tinydb_.py
  tests/cite/README.md
  tests/cite/canada-hydat-daily-mean-02HC003.geojson
  tests/cite/cite.config.yml
  tests/data/README.md
  tests/data/canada-hydat-daily-mean-02HC003.tinydb
  tests/test_tinydb_provider.py
Labels: enhancement, OGC API - Features

#1736 EDR: add HTML table of parameters for collections with EDR support (#1733)
  pygeoapi/templates/collections/collection.html
Labels: enhancement, OGC API - Environmental Data Retrieval

#1738 Solve issue #1737: links to list of jobs in json format
  pygeoapi/api/processes.py
Labels: bug, OGC API - Processes

#1730 Release Process Manager backed by Postgresql
  .github/workflows/main.yml
  pygeoapi/plugin.py
  pygeoapi/process/manager/postgresql.py
  requirements-manager.txt
  tests/data/postgres_manager_full_structure.backup.sql
  tests/pygeoapi-test-config-postgres-manager.yml
  tests/test_postgresql_manager.py
Labels: enhancement, OGC API - Processes

#1742 update jobs endpoint link title (#1739)
  pygeoapi/api/processes.py
Labels: bug, OGC API - Processes

#1743 Add TRS to pygeoapi config schema
  docs/source/configuration.rst
  pygeoapi/schemas/config/pygeoapi-config-0.x.yml
Labels: bug

#1747 Remove spatial parameter from OAS for single location
  pygeoapi/api/environmental_data_retrieval.py
Labels: bug

#1746 Document PostgreSQL process manager
  docs/source/data-publishing/ogcapi-processes.rst
Labels: documentation

#1727 Use consistent get_field ref in providers
  docs/source/plugins.rst
  pygeoapi/provider/base.py
  pygeoapi/provider/csv_.py
  pygeoapi/provider/csw_facade.py
  pygeoapi/provider/elasticsearch_.py
  pygeoapi/provider/erddap.py
  pygeoapi/provider/esri.py
  pygeoapi/provider/geojson.py
  pygeoapi/provider/mongo.py
  pygeoapi/provider/ogr.py
  pygeoapi/provider/oracle.py
  pygeoapi/provider/postgresql.py
  pygeoapi/provider/rasterio_.py
  pygeoapi/provider/sensorthings.py
  pygeoapi/provider/socrata.py
  pygeoapi/provider/sqlite.py
  pygeoapi/provider/tinydb_.py
  pygeoapi/provider/xarray_.py
  pygeoapi/provider/xarray_edr.py
Labels: enhancement

#1749 Render covjson or geojson in EDR HTML view
  pygeoapi/templates/collections/edr/query.html
Labels: enhancement, OGC API - Environmental Data Retrieval

#1751 Update test_postgresql_manager.py
  pygeoapi/process/manager/postgresql.py
  tests/test_postgresql_manager.py
Labels: bug, OGC API - Processes

#1754 fix pagination for features/records (#1658)
  pygeoapi/api/itemtypes.py
Labels: bug, OGC API - Features, OGC API - Records

#1755 add CORS expose headers setting (#1689)
  pygeoapi/flask_app.py
  pygeoapi/starlette_app.py
Labels: bug

#1756 OAProc: handle binary data when response: document (#1285)
  docs/source/data-publishing/ogcapi-processes.rst
  docs/source/plugins.rst
  pygeoapi/api/processes.py
Labels: enhancement, OGC API - Processes

#1757 raise error for collections without queryables
  pygeoapi/api/itemtypes.py
  tests/api/test_itemtypes.py
Labels: bug

#1744 Describe required collection level metadata about EDR Queries
  pygeoapi/api/__init__.py
Labels: enhancement, OGC API - Environmental Data Retrieval

#1758 safeguard OpenAPI detection on startup (#1650)
  pygeoapi/openapi.py
Labels: enhancement

#1759 OAProc: fix response: document encoding for results (#1579)
  pygeoapi/api/processes.py
  pygeoapi/process/manager/base.py
  pygeoapi/process/manager/dummy.py
  pygeoapi/util.py
  tests/api/test_processes.py
Labels: bug, OGC API - Processes

#1763 Fixed typo
  docs/source/configuration.rst
Labels: bug, documentation

#1761 fix various deprecation warnings
  pygeoapi/api/environmental_data_retrieval.py
  pygeoapi/provider/xarray_edr.py
Labels: bug

#1760 add installation note about Python version support (#1644)
  docs/source/installation.rst
Labels: documentation

#1768 Add Wallet for Session pool connections in oracle.py
  docs/source/data-publishing/ogcapi-features.rst
  pygeoapi/provider/oracle.py
Labels: enhancement
