Repository geopython/pygeoapi, pull requests merged in 2024-11, with the labels that each got.

#1838 fix HEAD requests for items (#1836)
  pygeoapi/flask_app.py
  pygeoapi/starlette_app.py
Labels: bug

#1839 add service contact to OpenAPI (#1835)
  pygeoapi/openapi.py
Labels: enhancement, OpenAPI

#1832 Lifted pin on sqlalchemy in order to be able to use v2+
  .github/workflows/main.yml
  pygeoapi/provider/postgresql.py
  requirements.txt
Labels: enhancement

#1846 Improved documentation about admin api
  docs/source/_static/openapi_admin.png
  docs/source/admin-api.rst
Labels: documentation

#1798 Fix bug when trying to get job result in binary format
  pygeoapi/process/manager/mongodb_.py
  pygeoapi/process/manager/postgresql.py
  pygeoapi/process/manager/tinydb_.py
  tests/test_manager.py
Labels: OGC API - Processes

#1827 Support EDR single item locations for Starlette
  pygeoapi/starlette_app.py
Labels: OGC API - Environmental Data Retrieval

#1852 update pygeoapi-auth info to security page
  docs/source/security.rst
Labels: documentation

#1822 Support empty default environment variable values
  pygeoapi/util.py
  tests/pygeoapi-test-config-envvars.yml
  tests/test_config.py
Labels: bug

#1854 Add Arabic Translation and RTL Support
  locale/ar/LC_MESSAGES/messages.po
  locale/bs/LC_MESSAGES/messages.po
  locale/de/LC_MESSAGES/messages.po
  locale/en/LC_MESSAGES/messages.po
  locale/es/LC_MESSAGES/messages.po
  locale/fr/LC_MESSAGES/messages.po
  locale/sr/LC_MESSAGES/messages.po
  pygeoapi/templates/_base.html
Labels: ui

#1859 Updated documentation about OGC API - Tiles Providers
  docs/source/data-publishing/ogcapi-tiles.rst
Labels: enhancement, documentation
