Repository geopython/pygeoapi, pull requests merged in 2025-06, with the labels that each got.

#2021 Use spec conform Storage CRS notation
  docs/source/crs.rst
  pygeoapi/api/__init__.py
  pygeoapi/api/itemtypes.py
  pygeoapi/templates/collections/collection.html
  tests/api/test_api.py
  tests/api/test_itemtypes.py
  tests/test_ogr_gpkg_provider.py
  tests/test_ogr_wfs_provider_live.py
Labels: OGC API - Features

#2034 typo leading to STAC examples not opening
  pygeoapi/api/stac.py
Labels: bug

#2004 MySQL OAF provider
  .github/workflows/main.yml
  docs/source/data-publishing/ogcapi-features.rst
  pygeoapi/plugin.py
  pygeoapi/process/manager/postgresql.py
  pygeoapi/provider/mvt_postgresql.py
  pygeoapi/provider/sql.py
  requirements-provider.txt
  tests/data/mysql_data.sql
  tests/test_mysql_provider.py
  tests/test_postgresql_provider.py
Labels: OGC API - Features

#2035 Pre-pull docker images in GitHub Actions
  .github/workflows/main.yml
Labels: enhancement, tests, packaging

#2038 add support for custom logo/icon to default HTML
  docs/source/configuration.rst
  docs/source/html-templating.rst
  pygeoapi/schemas/config/pygeoapi-config-0.x.yml
  pygeoapi/templates/_base.html
Labels: enhancement, ui

#2039 fix ref for icon/logo
  pygeoapi/templates/_base.html
Labels: bug, ui

#2014 Pydantic v1/2 compatibility
  Dockerfile
  pygeoapi/models/config.py
  pygeoapi/models/openapi.py
  requirements-django.txt
  requirements.txt
Labels: packaging

#2022 Implement native SQL Alchemy MVT
  .github/workflows/main.yml
  docs/source/data-publishing/ogcapi-tiles.rst
  pygeoapi/api/tiles.py
  pygeoapi/provider/mvt_postgresql.py
  pygeoapi/provider/sql.py
  pygeoapi/provider/tile.py
  pygeoapi/templates/collections/tiles/index.html
  tests/test_postgresql_mvt_provider.py
Labels: OGC API - Tiles, ui
